{% set name = "dxtbx" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cctbx/dxtbx/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 14dd6b897e080dd9babfe00a08ebe1cc1cd999be0d73676029c5c08e8835d57d
  folder: dxtbx

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost
    - cctbx-base >=2021.12
    - hdf5
    - numpy 1.19,<1.21|>=1.21.5
    - pip
    - pybind11
    - python
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('cctbx-base') }}
    - {{ pin_compatible('hdf5') }}
    - h5py
    - hdf5plugin
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pint
    - procrunner
    - pycbf
    - python
    - python-dateutil >=2.7.0
    - scipy
    - tqdm

test:
  source_files:
    - dxtbx/tests
    - dxtbx/conftest.py
  requires:
    - dials-data
    - pytest <7
    - pytest-mock
    - pip
  imports:
    - dxtbx.ext
  commands:
    - pytest $SRC_DIR/dxtbx/tests --regression
    - pip check

about:
  home: https://github.com/cctbx/dxtbx
  license: BSD-3-Clause
  license_family: BSD
  license_file: dxtbx/LICENSE.txt
  summary: Diffraction Experiment Toolbox
  description: |
    A cctbx-style toolbox to describe single-crystal diffraction experiments,
    where a monochromatic beam is used to illuminate a sample which is rotated
    during the exposure and diffraction recorded on a flat area detector.
  doc_url: https://dials.github.io/documentation/index.html
  dev_url: https://github.com/cctbx/dxtbx

extra:
  recipe-maintainers:
    - ndevenish
    - rjgildea
    - anthchirp
